---
output: html_document
---
THIS WORKS!!! OMG

Setting working directory and loading data
```{r, echo = F}
setwd("/Users/ricksimpson/Documents/Spring 2015/scientific_computing")
data <- read.csv("gapminderDataFiveYear.txt", sep="\t")
```

Now subseting out three coutnries and plotting their GDPs by year
```{r, echo = F}
panama <- subset(data,data$country=="Panama")
japan <- subset(data,data$country=="Japan")
canada <- subset(data,data$country=="Canada")

plot(panama$gdpPercap~panama$year, ylab="GDP", xlab="year", pch=19)
plot(japan$gdpPercap~japan$year, ylab="GDP", xlab="year", pch=19)
plot(canada$gdpPercap~canada$year, ylab="GDP", xlab="year", pch=19)
```

Now calculating the means, min, and max values per continent, and creating a histograms for life expectancy
```{r, echo = FALSE}
#echo = F means that the R code won't appear in the final knit document
means <- tapply(data$lifeExp, data$continent, mean)
means
min <- tapply(data$lifeExp, data$continent, min)
min
max <- tapply(data$lifeExp, data$continent, max)
max

hist(data$lifeExp)
hist(data$lifeExp, breaks=50)
```
